modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="dtv"
version="1.0.0"
displayName="Dynamic Trees: Valoria"
authors="Almalexy"
description='''Adds Dynamic Trees support and biome integration for Valoria dimension.'''
displayTest="MATCH_VERSION"

# --- зависимости ---

[[dependencies.dtv]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.dtv]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.dtv]]
modId="dynamictrees"
mandatory=true
versionRange="[1.4.7,)"
ordering="AFTER"
side="BOTH"

[[dependencies.dtv]]
modId="valoria"
mandatory=true
versionRange="[1.0.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.dtv]]
modId="terrablender"
mandatory=true
versionRange="[3.0.1.10,)"
ordering="AFTER"
side="BOTH"